version: '3.8'

services:
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue_frontend_prod
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      - VITE_CLIENT_API_URL=http://localhost:8000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
